pnpEnableEsmLoader: true

packageExtensions:
  '@angular-devkit/core@*':
    dependencies:
      chokidar: '*'
  '@babel/register@*':
    dependencies:
      '@babel/core': '*'
  '@jest/test-result@*':
    dependencies:
      jest-haste-map: '*'
      jest-resolve: '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  '@rollup/pluginutils@*':
    dependencies:
      '@types/estree': '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  import-sort-parser-typescript@*:
    dependencies:
      import-sort-parser: '*'
  import-sort-style@*:
    dependencies:
      import-sort-parser: '*'
  ink-multi-select@*:
    dependencies:
      ink: '*'
      react: '*'
  ink@*:
    dependencies:
      '@types/react': '*'
      '@types/yoga-layout': '*'
  jest-resolve@*:
    dependencies:
      jest-haste-map: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  rollup-plugin-analyzer@*:
    dependencies:
      rollup: '*'
  webpack-chain@*:
    dependencies:
      tapable: 1.1.3
      webpack: 4.44.2
  webpack@*:
    dependencies:
      json-schema: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-esm-loader-typescript.cjs
    spec: 'https://github.com/kherock/yarn-plugins/releases/download/v23.2.0/plugin-esm-loader-typescript.js'

yarnPath: yarn/cli/src/cli.dev.mjs
