pnpEnableEsmLoader: true

enableGlobalCache: false

packageExtensions:
  pkg-tests-core@*:
    dependencies:
      '@yarnpkg/core': '4.0.0-rc.42'
      '@yarnpkg/fslib': '*'
      '@yarnpkg/parsers': '*'
      '@jest/globals': '*'
      finalhandler: '*'
      invariant: '*'
      pem: 'dexus/pem'
      semver: '*'
      serve-static: '*'
      super-resolve: '*'
      minimatch: '*'
      tar-fs: '*'
      tslib: '*'
      uuid: '*'
      klaw: '*'
  pkg-tests-fixtures@*:
    dependencies:
      '@yarnpkg/fslib': '*'
  '@yarnpkg/plugin-pack@*':
    dependencies:
      '@yarnpkg/cli': '*'
  '@yarnpkg/plugin-stage@*':
    dependencies:
      '@yarnpkg/cli': '*'
  '@yarnpkg/plugin-pnp@*':
    dependencies:
      '@yarnpkg/cli': '*'
  '@angular-devkit/core@*':
    dependencies:
      chokidar: '*'
  '@babel/register@*':
    dependencies:
      '@babel/core': '*'
  '@jest/test-result@*':
    dependencies:
      jest-haste-map: '*'
      jest-resolve: '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  '@rollup/pluginutils@*':
    dependencies:
      '@types/estree': '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  import-sort-parser-typescript@*:
    dependencies:
      import-sort-parser: '*'
  import-sort-style@*:
    dependencies:
      import-sort-parser: '*'
  ink-multi-select@*:
    dependencies:
      ink: '*'
      react: '*'
  ink@*:
    dependencies:
      '@types/react': '*'
      '@types/yoga-layout': '*'
  jest-resolve@*:
    dependencies:
      jest-haste-map: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  rollup-plugin-analyzer@*:
    dependencies:
      rollup: '*'
  webpack-chain-5@*:
    dependencies:
      webpack: '*'
  webpack@*:
    dependencies:
      json-schema: '*'
  '@svgr/babel-plugin-transform-svg-component@*':
    dependencies:
      '@babel/template': '*'
  '@svgr/core@*':
    dependencies:
      prettier: '*'
      svgo: '*'

plugins:
  - path: yarn/plugin-pnp-patch/bundles/@yarnpkg/plugin-pnp-patch.cjs

yarnPath: yarn/cli/src/cli.dev.mjs
