packageExtensions:
  '@babel/register@*':
    dependencies:
      '@babel/core': '*'
  '@commitlint/types@*':
    dependencies:
      chalk: '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  import-sort-parser-typescript@*:
    dependencies:
      import-sort-parser: '*'
  import-sort-style@*:
    dependencies:
      import-sort-parser: '*'
  jest-resolve@*:
    dependencies:
      jest-haste-map: '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  webpack-chain@*:
    dependencies:
      tapable: '*'
      webpack: 4.44.2
  webpack@*:
    dependencies:
      json-schema: '*'
  ink@*:
    dependencies:
      '@types/yoga-layout': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  #- yarn/plugin-essentials/dist/@monstrs/plugin-essentials.js

yarnPath: .yarn/releases/yarn-2.4.1.cjs
