plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-2.1.1.js

packageExtensions:
  jest-resolve@*:
    dependencies:
      jest-haste-map: '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  '@commitlint/types@*':
    dependencies:
      chalk: '*'
  '@babel/register@*':
    dependencies:
      '@babel/core': '*'
  'webpack-chain@*':
    dependencies:
      'tapable': '*'
      'webpack': '*'
