compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  '@actions/github@*':
    dependencies:
      undici: '*'
  '@jest/test-result@*':
    dependencies:
      jest-haste-map: '*'
      jest-resolve: '*'
  '@monstrs/mikro-orm-logger@*':
    dependencies:
      '@mikro-orm/core': '*'
  '@monstrs/stack-trace@*':
    dependencies:
      '@types/stack-utils': '*'
  '@octokit/plugin-paginate-rest@*':
    dependencies:
      '@octokit/core': '*'
  '@svgr/babel-plugin-transform-svg-component@*':
    dependencies:
      '@babel/template': '*'
      '@types/babel__template': '*'
  '@svgr/core@*':
    dependencies:
      '@types/babel__core': '*'
      '@types/prettier': '*'
      prettier: '*'
      svgo: '*'
  '@yarnpkg/core@*':
    dependencies:
      '@types/lodash': '*'
  '@yarnpkg/plugin-npm-cli@*':
    dependencies:
      '@yarnpkg/plugin-pack': '*'
      '@yarnpkg/plugin-npm': '*'
      '@yarnpkg/cli': '*'
  '@yarnpkg/plugin-npm@*':
    dependencies:
      '@yarnpkg/plugin-pack': '*'
  '@yarnpkg/plugin-pack@*':
    dependencies:
      '@yarnpkg/cli': '*'
  '@yarnpkg/plugin-pnp@*':
    dependencies:
      '@yarnpkg/cli': '*'
  '@yarnpkg/plugin-stage@*':
    dependencies:
      '@yarnpkg/cli': '*'
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  import-sort-parser-typescript@*:
    dependencies:
      import-sort-parser: '*'
  import-sort-style@*:
    dependencies:
      import-sort-parser: '*'
  ink-multi-select@*:
    dependencies:
      '@types/react': '*'
      ink: '*'
      react: '*'
  ink@*:
    dependencies:
      '@types/react': '*'
      '@types/react-reconciler': '*'
      '@types/yoga-layout': '*'
  node-fetch@*:
    dependencies:
      encoding: '*'
  webpack-chain-5@*:
    dependencies:
      webpack: '*'
  webpack@*:
    dependencies:
      json-schema: '*'
  '@inkjs/ui@*':
    peerDependencies:
      react: '*'
  'ink-link@*':
    dependencies:
      react: '*'

plugins:
  - path: yarn/plugin-pnp-patch/bundles/@yarnpkg/plugin-pnp-patch.cjs

pnpEnableEsmLoader: true

yarnPath: yarn/cli/src/cli.dev.mjs
