api = "0.2"

[buildpack]
id = "tech.monstrs.buildpacks.yarn-workspace-start"
version = "0.0.2"
name = "Yarn Workspace Start Buildpack"

[metadata]
include_files = ["dist", "bin/build", "bin/detect", "buildpack.toml"]
pre_package = "yarn build"

[[stacks]]
id = "tech.monstrs.stacks.node"
