api = "0.2"

[buildpack]
id = "tech.monstrs.buildpacks.yarn-workspace-node-options"
version = "0.0.3"
name = "Yarn Workspace Node Options Buildpack"

[metadata]
include_files = ["dist", "bin/build", "bin/detect", "buildpack.toml"]
pre_package = "yarn build"

[[stacks]]
id = "tech.monstrs.stacks.node"

[[stacks]]
id = "tech.monstrs.stacks.node-static"

[[stacks]]
id = "tech.monstrs.stacks.operator"
