name: Checks

on: [pull_request]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22.5'

      - name: Install
        run: source .env && export NODE_OPTIONS && yarn install

      - name: Build
        run: source .env && export NODE_OPTIONS && yarn cli:build

      - name: Lint
        run: source .env && export NODE_OPTIONS && yarn checks lint
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: TypeCheck
        run: source .env && export NODE_OPTIONS && yarn checks typecheck
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: TestUnit
        run: source .env && export NODE_OPTIONS && yarn checks test unit
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: TestIntegration
        run: source .env && export NODE_OPTIONS && yarn checks test integration
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Release
        run: source .env && export NODE_OPTIONS && yarn checks release
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
