name: Checks

on: [pull_request]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13'

      - name: Install
        run: yarn install

      - name: Changes
        run: yarn files changed list
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Run
        run: yarn checks run
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
