name: Notify

on:
  workflow_run:
    workflows:
      - Publish
    types:
      - completed

jobs:
  run:
    name: Notify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Notify
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const { version } = JSON.parse(require('fs').readFileSync('yarn/cli/package.json', 'utf8'))

            const repos = [
              'common-modules',
              'telemetry-modules',
              'mikro-orm-modules',
              'nestjs-modules',
              'nextjs-modules',
              'react-modules',
              'buildpacks',
              'rpc-modules',
              'protobuf-modules',
              'types',
              'ui',
            ]

            for await (repo of repos) {
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo,
                workflow_id: 'tools.yaml',
                ref: 'master',
                inputs: {
                  version,
                }
              })

              await require('node:timers/promises').setTimeout(15000)
            }
