name: Publish

on:
  workflow_dispatch:

jobs:
  run:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '19.8'

      - name: Install
        run: NODE_OPTIONS='-r /home/runner/work/tools/tools/.pnp.cjs --loader /home/runner/work/tools/tools/.pnp.loader.mjs' yarn install

      - name: Npm Publish
        run: |
          NODE_OPTIONS='-r /home/runner/work/tools/tools/.pnp.cjs --loader /home/runner/work/tools/tools/.pnp.loader.mjs' yarn version apply --all
          NODE_OPTIONS='-r /home/runner/work/tools/tools/.pnp.cjs --loader /home/runner/work/tools/tools/.pnp.loader.mjs' yarn workspaces changed foreach --verbose --topological --no-private npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore(common): publish'
          branch: master
