name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  run:
    name: Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install
        run: source .env && export NODE_OPTIONS && yarn install
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Version
        run: source .env && export NODE_OPTIONS && yarn workspaces changed foreach --no-private --verbose version patch --deferred
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore(common): versions'
